name: Monty Bambino
favicon: null
layout_spectrum: 0.24708924256265163
typography_spectrum: 0.20518954377621412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5523924182634801
  lightness: 0.5295602076221257
  saturation: 0.05160080804489553
  rhythmicContrast: 0.3127852063626051
purpose: []
